Repository AY2425S2-CS2103-F10-2/tp, pull requests merged in 2025-03, with the labels that each got.

#45 Add Birthday field including changes to AddCommand, EditCommand and S…
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#54 Display birthday field in Client Overview
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: type.Task

#65 Redesign Help UI box to display a list of commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Medium:

#75 Add support for resizing Help UI box
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, priority.Medium:

#87 Add Command History
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Enhancement, priority.Medium:

#98 Fix Help UI box size
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug, severity.VeryLow

#106 Add new commands in help UI window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#105 Add user profile feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/user/UserProfile.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ProfileCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ClientNestParser.java
  src/main/java/seedu/address/logic/parser/ProfileCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/storage/JsonSerializableUserProfile.java
  src/main/java/seedu/address/storage/JsonUserProfileStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserProfileStorage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/UserProfilePanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/UserProfilePanel.fxml
  src/test/java/seedu/address/commons/core/user/UserProfileTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPolicyCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ProfileCommandTest.java
  src/test/java/seedu/address/logic/parser/ProfileCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonSerializableUserProfileTest.java
  src/test/java/seedu/address/storage/JsonUserProfileStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Epic

#120 Update UI UML Diagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/Ui.png
Labels: type.Task, priority.High

#123 Fix ProfileCommand and UserProfilePanel updating bug
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UserProfilePanel.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.Medium

#126 Add UML Diagram as image
  docs/DeveloperGuide.md
  docs/images/diagrams/UiClassDiagram.png
Labels: type.Task, priority.High

#137 Convert PUML files to PNG and update DG to match
  docs/DeveloperGuide.md
  docs/images/diagrams/ArchitectureDiagram.png
  docs/images/diagrams/ArchitectureSequenceDiagram.png
  docs/images/diagrams/CommitActivityDiagram.png
  docs/images/diagrams/ComponentManagers.png
  docs/images/diagrams/DeleteSequenceDiagram.png
  docs/images/diagrams/LogicClassDiagram.png
  docs/images/diagrams/ModelClassDiagram.png
  docs/images/diagrams/ParserClasses.png
  docs/images/diagrams/UndoRedoState0.png
  docs/images/diagrams/UndoRedoState1.png
  docs/images/diagrams/UndoRedoState2.png
  docs/images/diagrams/UndoRedoState3.png
  docs/images/diagrams/UndoRedoState4.png
  docs/images/diagrams/UndoRedoState5.png
  docs/images/diagrams/UndoSequenceDiagram-Logic.png
  docs/images/diagrams/UndoSequenceDiagram-Model.png
Labels: type.Task, priority.High

#145 Update Model Class UML Diagram
  docs/diagrams/ModelClassDiagram.puml
  docs/images/diagrams/ModelClassDiagram.png
Labels: type.Task

#154 Update and refresh the UI
  docs/DeveloperGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/ui/UpcomingBirthdayCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PolicyListCard.fxml
  src/main/resources/view/PolicyListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/UpcomingBirthdayCard.fxml
  src/main/resources/view/UpcomingBirthdaysPanel.fxml
  src/main/resources/view/UserProfilePanel.fxml
Labels: type.Task, priority.Medium:
