Repository AY2425S2-CS2103-F10-2/tp, pull requests merged in 2025-04, with the labels that each got.

#163 Fix alpha-testing bug
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListPolicyCommand.java
  src/main/java/seedu/address/logic/parser/ClientNestParser.java
  src/main/java/seedu/address/model/policy/PolicyLink.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/test/java/seedu/address/logic/parser/ClientNestParserTest.java
  src/test/java/seedu/address/model/policy/PolicyLinkTest.java
Labels: priority.High, severity.High

#171 Update UI design for task list
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskManagerWindow.fxml
Labels: type.Task

#176 Update User Guide to include User Profile Feature
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAliceDoeResult.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/commons/core/user/UserProfile.java
  src/test/java/seedu/address/commons/core/user/UserProfileTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task

#180 Fix UI styling issues
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAliceDoeResult.png
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/UpcomingBirthdayCard.fxml
Labels: type.Task, severity.Medium

#184 Update Help page to include Add and Delete PR commands
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#232 Fix bugs discovered by PE-D
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PolicyListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Bug, priority.High, severity.High

#231 Fix Issues found during dry run PE
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/leedeen01.md
  src/main/java/seedu/address/logic/Messages.java
Labels: priority.High

#235 Add default values for address and policy book
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonPolicyBookStorage.java
  src/main/java/seedu/address/storage/PolicyBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonAddressBookStorageTest/NonExistentFile.json
  src/test/data/JsonPolicyBookStorageTest/NonExistentFile.json
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonPolicyBookStorageTest.java
Labels: type.Enhancement, priority.High, severity.Low

#238 Add test cases for default book creations
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonAddressBookStorageTest/nonExistentFile.json
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonPolicyBookStorageTest.java
Labels: type.Task

#240 Update User Guide and fix UI styling issues
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UserProfilePanel.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PolicyListCard.fxml
Labels: type.Bug, priority.High

#242 Update product website
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/index.md
  docs/site.json
Labels: type.Enhancement, priority.High

#245 Update team portfolio pages
  docs/index.md
  docs/team/fabianheng.md
  docs/team/leedeen01.md
  docs/team/nightlyaffair.md
  docs/team/teesha902.md
Labels: type.Enhancement, priority.Medium:

#258 Add Status Bar Footer known issue in UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task
